[package]
name = "orx-pseudo-default"
version = "2.1.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "PseudoDefault trait allows to create a cheap default instance of a type, which does not claim to be useful."
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-pseudo-default/"
keywords = ["default", "pseudo", "uninitialized", "swap"]
categories = ["data-structures", "rust-patterns", "no-std"]

[dependencies]
orx-pseudo-default-derive = { path = "../orx-pseudo-default-derive", optional = true }

[features]
default = ["std", "derive"]
std = []
derive = ["orx-pseudo-default-derive"]
